### ISSUE TITLE
 dll. is not compaitable for WINCE-2013 

### ISSUE THREAD

**Issue by ashu3123** [HW71/ManagedOpenSSL.net#1]
This .dll is not compaitable with WINCE-2013 .can you tell us the step for compilation of openssl.net for wince-2013?

**Comment by HW71** [comment]
Sorry, personally I never worked with Windows CE - nor do I have any access to devices running it. Hence I won't be able to support you with that. But just to make sure: it's not just the managed part of this project you'd need to recompile - you also need to get the unmanaged part (libeay32.dll and ssleay32.dll) up and running for this OS. Or do you have this already covered?

**Comment by ashu3123** [comment]
Hi,
Thanks for the reply actually I have followed all the step mentioned in git
hub page. But in my code the ssl library init() and other function's
related to ssl don't get initialised.
So is there any way by which I can compile the library for wince-2013 or
any other way by which secure connection can be created.

**Comment by HW71** [comment]
Hi, I did some further research and found that for Windows CE there was a special version of the .NET Framework available (.NET Compact Framework). So you need to check the possibilities to recompile both managed and unmanaged part for Window CE. As I said: I would like to help you with that, but since I don't have access to a device running Windows CE my options are "limited", so to say... :-(

**Comment by ashu3123** [comment]
Thanks for the reply. Can you tell me how to compile this library for
WINCE-2013.

**Comment by ashu3123** [comment]
I mean steps for compilation of managed open SSL.

**Comment by HW71** [comment]
Hi Ashu, as outlined above I never worked with Windows CE. Sorry! I would have to "Google" for this topic, too. I did that now with search terms "Windows CE 2013 Visual Studio" and found for example the following page: 

https://devblogs.microsoft.com/visualstudio/windows-embedded-compact-2013-now-available-for-visual-studio-2013/

According to this you _might_ be able to recompile the DLL using Visual Studio 2013. Maybe you need to do that based on the VS 2008 project and solution files.

Please check other search results, too...

Hope this helps somehow & good luck!

**Comment by HW71** [comment]
Closing this issue since I can't provide any further help here...
